# Generated by Django 5.2.1 on 2025-05-17 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_order_item_orderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('cash', 'Tiền mặt khi nhận hàng (COD)')], default='paypal', max_length=20),
        ),
    ]
